# Auto-generated by gen_stress_hex.py — do not edit.
PASS_PC       = 0x000015a0
FAIL_PC       = 0x000015a8
MAIN_PC       = 0x00001028
OUTER_LOOP_PC = 0x00001084
BM_CPU_WI     = 256   # SRAM word index for CPU burst cycles
BM_DMA_WI     = 257   # SRAM word index for DMA cycles
BM_GPU_WI     = 258   # SRAM word index for GPU cycles
TIMER_WI      = 259   # SRAM word index for timer snapshot
ITER_WI       = 260   # SRAM word index for iteration counter
STRESS_ITER   = 10
BURST_N_WORDS = 32
GPU_N_WORDS   = 8
BUF_A_WI      = 0
BUF_B_WI      = 32
GPU_SRC_WI    = 64
GPU_DST_WI    = 80
KERNEL_WI     = 128
