"""Negative controls for tools/dft/check_scan_clk_rst.py (bead claude_verilog_test-j41m.2).

The checker proves, on a flattened netlist, that in scan mode every async reset is
tester-controlled and every flop is test-clocked. A checker that cannot fail proves nothing, so
each test here builds a tiny design, runs the real tool through yosys and asserts the exit code:

* a correctly muxed design passes;
* one un-muxed reset, one un-muxed clock, and a flop-generated reset each fail;
* the ``--expect-gates`` guard fails a design whose muxes were optimised away;
* a netlist that instantiates an undefined cell fails instead of passing vacuously.

Needs yosys (``$YOSYS`` or on ``PATH``); skipped otherwise, so the plain pytest job is unaffected.
"""

import os
import shutil
import subprocess
import sys
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parents[2]
CHECKER = REPO / "tools" / "dft" / "check_scan_clk_rst.py"
YOSYS = os.environ.get("YOSYS") or shutil.which("yosys")

pytestmark = pytest.mark.skipif(YOSYS is None, reason="yosys not available")

_HEAD = """
module top (
    input  wire clk_i, input wire rst_ni, input wire scan_mode_i,
    input  wire scan_clk_i, input wire scan_rst_ni, input wire d,
    output reg  q
);
"""
_FLOP = """
    always @(posedge clk_w or negedge rst_w)
        if (!rst_w) q <= 1'b0; else q <= d;
endmodule
"""
_CLK_MUXED = "    wire clk_w = scan_mode_i ? scan_clk_i : clk_i;\n"
_CLK_BARE = "    wire clk_w = clk_i;\n"
_RST_MUXED = "    wire rst_w = scan_mode_i ? scan_rst_ni : rst_ni;\n"
_RST_BARE = "    wire rst_w = rst_ni;\n"
# a reset generated by a flop with no scan override: it toggles while the chains shift
_RST_FLOP = (
    "    reg r_q;\n"
    "    always @(posedge clk_i or negedge rst_ni) if (!rst_ni) r_q <= 1'b0; else r_q <= 1'b1;\n"
    "    wire rst_w = r_q;\n"
)


def _run(tmp_path: Path, body: str, *extra: str) -> subprocess.CompletedProcess:
    netlist = tmp_path / "top.v"
    netlist.write_text(_HEAD + body + _FLOP)
    env = dict(os.environ, YOSYS=str(YOSYS))
    return subprocess.run(
        [sys.executable, str(CHECKER), "--netlist", str(netlist), "--top", "top", *extra],
        capture_output=True,
        text=True,
        env=env,
        check=False,
    )


def test_muxed_design_passes(tmp_path: Path) -> None:
    res = _run(tmp_path, _CLK_MUXED + _RST_MUXED, "--expect-gates", "2")
    assert res.returncode == 0, res.stdout
    assert "violations: 0" in res.stdout


def test_unmuxed_reset_pin_trips_only_the_gate_count(tmp_path: Path) -> None:
    # A bare reset PIN is tester-controllable by construction, so the cone check accepts it; what
    # catches the removed mux is the --expect-gates count.
    res = _run(tmp_path, _CLK_MUXED + _RST_BARE)
    assert res.returncode == 0, res.stdout
    res2 = _run(tmp_path, _CLK_MUXED + _RST_BARE, "--expect-gates", "2")
    assert res2.returncode == 1, res2.stdout
    assert "expected at least 2 scan-mode muxes" in res2.stdout


def test_flop_generated_unmuxed_reset_fails(tmp_path: Path) -> None:
    res = _run(tmp_path, _CLK_MUXED + _RST_FLOP)
    assert res.returncode == 1, res.stdout
    assert "reset is generated by sequential cell" in res.stdout


def test_unmuxed_clock_fails(tmp_path: Path) -> None:
    res = _run(tmp_path, _CLK_BARE + _RST_MUXED)
    assert res.returncode == 1, res.stdout
    assert "without a scan-mode mux" in res.stdout


def test_expect_gates_guard_fails_when_muxes_missing(tmp_path: Path) -> None:
    res = _run(tmp_path, _CLK_MUXED + _RST_MUXED, "--expect-gates", "3")
    assert res.returncode == 1, res.stdout
    assert "expected at least 3 scan-mode muxes" in res.stdout


def test_undefined_cell_fails_instead_of_passing_vacuously(tmp_path: Path) -> None:
    """An undefined cell has no port directions, so its outputs would never be traced."""
    body = _CLK_MUXED + _RST_MUXED + "    wire g;\n    mystery_cell u_x (.a(clk_i), .y(g));\n"
    res = _run(tmp_path, body)
    assert res.returncode == 1, res.stdout
    assert "no definition" in res.stdout
