# ============================================================
# CP Array Layout using sky130 gencell device generators
# Fix-request: sky130-pv-fr001 (CP block only)
# Tool: Magic 8.3.489 + sky130A device generators
# run_id: layout_20260620_FR001
#
# Circuit (sky130_cp.sp):
#   PMOS bias:  M_pbias  pfet_01v8 W=4u/L=2u nf=4  (diode-connected)
#   PMOS mirror:M_psrc   pfet_01v8 W=4u/L=2u nf=4  (1:1 mirror)
#   NMOS bias:  M_nbias  nfet_01v8 W=1.5u/L=2u nf=1 (diode-connected)
#   NMOS mirror:M_nsrc   nfet_01v8 W=1.5u/L=2u nf=1 (1:1 mirror)
#
# Common-centroid arrangement:
#   PMOS: [Dum | M_pbias_A | M_psrc_A | M_psrc_B | M_pbias_B | Dum]
#   NMOS: [Dum | M_nbias_A | M_nsrc_A | M_nsrc_B | M_nbias_B | Dum]
#
# Each primitive cell is generated by sky130 device generator with
# guard=1, which includes an integrated guard ring with nwell tap
# (for PMOS) or psub tap (for NMOS), satisfying nwell.4 and LU rules.
#
# APPROACH: Generate primitive single-instance cells first, then build
# the array cells by placing instances of the primitives.
# ============================================================

tech load /home/neuromorphic/.volare/sky130A/libs.tech/magic/sky130A.tech
source /home/neuromorphic/.volare/sky130A/libs.tech/magic/sky130A.tcl
addpath /home/neuromorphic/.volare/sky130A/libs.ref/sky130_fd_pr/mag

set MAGDIR /home/neuromorphic/Downloads/Github/claude_verilog_test/analog/pll_clkgen/sky130/layout/mag

# ============================================================
# STEP 1: Generate PMOS primitive cell (W=4u, L=2u, nf=4)
#   guard=1 gives integrated guard ring with nwell tap (nwell.4 fix)
# ============================================================
puts "=== Generating PMOS primitive W=4u L=2u nf=4 ==="
set pfet_def [sky130::sky130_fd_pr__pfet_01v8_defaults]
dict set pfet_def w  4.0
dict set pfet_def l  2.0
dict set pfet_def nf 4
dict set pfet_def m  1
dict set pfet_def guard 1

cellname create pfet_4u_2u_nf4
load pfet_4u_2u_nf4
sky130::sky130_fd_pr__pfet_01v8_draw $pfet_def
save pfet_4u_2u_nf4

drc euclidean on
drc check
set p_drc [drc list count total]
puts "pfet_4u_2u_nf4 DRC: $p_drc violations"

# Get cell bounding box using select all + box
select top cell
expand
select all
set p_bb [box values]
set px0 [lindex $p_bb 0]; set py0 [lindex $p_bb 1]
set px1 [lindex $p_bb 2]; set py1 [lindex $p_bb 3]
set p_cell_w [expr {$px1 - $px0}]
set p_cell_h [expr {$py1 - $py0}]
puts "pfet_4u_2u_nf4 size: [expr {$p_cell_w*0.01}]um x [expr {$p_cell_h*0.01}]um (${p_cell_w}mu x ${p_cell_h}mu)"

# ============================================================
# STEP 2: Generate NMOS primitive cell (W=1.5u, L=2u, nf=1)
#   guard=1 gives integrated guard ring with psub tap (LU fix)
# ============================================================
puts "=== Generating NMOS primitive W=1.5u L=2u nf=1 ==="
set nfet_def [sky130::sky130_fd_pr__nfet_01v8_defaults]
dict set nfet_def w  1.5
dict set nfet_def l  2.0
dict set nfet_def nf 1
dict set nfet_def m  1
dict set nfet_def guard 1

cellname create nfet_1p5u_2u_nf1
load nfet_1p5u_2u_nf1
sky130::sky130_fd_pr__nfet_01v8_draw $nfet_def
save nfet_1p5u_2u_nf1

drc euclidean on
drc check
set n_drc [drc list count total]
puts "nfet_1p5u_2u_nf1 DRC: $n_drc violations"

select top cell
expand
select all
set n_bb [box values]
set nx0 [lindex $n_bb 0]; set ny0 [lindex $n_bb 1]
set nx1 [lindex $n_bb 2]; set ny1 [lindex $n_bb 3]
set n_cell_w [expr {$nx1 - $nx0}]
set n_cell_h [expr {$ny1 - $ny0}]
puts "nfet_1p5u_2u_nf1 size: [expr {$n_cell_w*0.01}]um x [expr {$n_cell_h*0.01}]um (${n_cell_w}mu x ${n_cell_h}mu)"

# ============================================================
# STEP 3: Generate PMOS DUMMY cell (same size, same type)
# ============================================================
puts "=== Generating PMOS dummy cell ==="
set pfet_dum [sky130::sky130_fd_pr__pfet_01v8_defaults]
dict set pfet_dum w  4.0
dict set pfet_dum l  2.0
dict set pfet_dum nf 4
dict set pfet_dum m  1
dict set pfet_dum guard 1

cellname create pfet_4u_2u_dum
load pfet_4u_2u_dum
sky130::sky130_fd_pr__pfet_01v8_draw $pfet_dum
save pfet_4u_2u_dum
puts "pfet_4u_2u_dum saved"

# ============================================================
# STEP 4: Generate NMOS DUMMY cell
# ============================================================
puts "=== Generating NMOS dummy cell ==="
set nfet_dum [sky130::sky130_fd_pr__nfet_01v8_defaults]
dict set nfet_dum w  1.5
dict set nfet_dum l  2.0
dict set nfet_dum nf 1
dict set nfet_dum m  1
dict set nfet_dum guard 1

cellname create nfet_1p5u_2u_dum
load nfet_1p5u_2u_dum
sky130::sky130_fd_pr__nfet_01v8_draw $nfet_dum
save nfet_1p5u_2u_dum
puts "nfet_1p5u_2u_dum saved"

# ============================================================
# STEP 5: Build cp_pmos_array
#
# Common-centroid arrangement (6 PMOS instances):
#   Position 0: Dum     (pfet_4u_2u_dum)
#   Position 1: pbias_A (pfet_4u_2u_nf4) — M_pbias finger A
#   Position 2: psrc_A  (pfet_4u_2u_nf4) — M_psrc  finger A
#   Position 3: psrc_B  (pfet_4u_2u_nf4) — M_psrc  finger B
#   Position 4: pbias_B (pfet_4u_2u_nf4) — M_pbias finger B
#   Position 5: Dum     (pfet_4u_2u_dum)
#
# Each cell placed at x = i * p_cell_w (abutted, guard ring shared).
# The generator includes the guard ring which has nwell + nwell tap.
# Adding a gap of 50mu (0.5um) between cells for independent well rings.
# ============================================================
puts "=== Building cp_pmos_array ==="
cellname create cp_pmos_array
load cp_pmos_array

# Gap between cell instances (needed so guard rings don't short)
# Actually with guard=1 each cell has its own complete guard ring.
# We need spacing >= 0 to avoid DRC between adjacent well/diff regions.
# Use gap = 0 first (abutted) - generator should handle this.
set p_gap 0

set p_order {pfet_4u_2u_dum pfet_4u_2u_nf4 pfet_4u_2u_nf4 pfet_4u_2u_nf4 pfet_4u_2u_nf4 pfet_4u_2u_dum}
set p_roles {DUM PBIAS_A PSRC_A PSRC_B PBIAS_B DUM}

set xi 0
set i 0
foreach cell $p_order role $p_roles {
    set xpos [expr {$xi - $px0}]
    set ypos [expr {0 - $py0}]
    # Place instance at (xpos, ypos)
    getcell $cell
    move origin $xpos $ypos
    puts "  Placed $cell ($role) at ([expr {$xpos*0.01}]um, [expr {$ypos*0.01}]um)"
    set xi [expr {$xi + $p_cell_w + $p_gap}]
    incr i
}

# Add port labels for the CP array
# The matched devices (pbias/psrc) drains form the circuit nodes
# We label at the center of each device instance for LVS
set total_p_w [expr {6 * $p_cell_w}]
set mid_y [expr {($p_cell_h - $py0 - $py0) / 2}]

# PMOS array ports
label "VDD" center [expr {$total_p_w / 2}] [expr {$p_cell_h + 50}]
label "pbias" center [expr {$p_cell_w + $p_cell_w/2}] $mid_y
label "pbias" center [expr {4 * $p_cell_w + $p_cell_w/2}] $mid_y
label "psrc_g" center [expr {2 * $p_cell_w + $p_cell_w/2}] $mid_y
label "psrc_g" center [expr {3 * $p_cell_w + $p_cell_w/2}] $mid_y

save cp_pmos_array
puts "cp_pmos_array saved with [expr {6}] pfet instances in common-centroid"

# DRC on the array
drc euclidean on
drc check
set cp_pmos_drc [drc list count total]
puts "cp_pmos_array DRC: $cp_pmos_drc violations"

# ============================================================
# STEP 6: Build cp_nmos_array
#
# Common-centroid arrangement (6 NMOS instances):
#   Position 0: Dum     (nfet_1p5u_2u_dum)
#   Position 1: nbias_A (nfet_1p5u_2u_nf1)
#   Position 2: nsrc_A  (nfet_1p5u_2u_nf1)
#   Position 3: nsrc_B  (nfet_1p5u_2u_nf1)
#   Position 4: nbias_B (nfet_1p5u_2u_nf1)
#   Position 5: Dum     (nfet_1p5u_2u_dum)
# ============================================================
puts "=== Building cp_nmos_array ==="
cellname create cp_nmos_array
load cp_nmos_array

set n_gap 0

set n_order {nfet_1p5u_2u_dum nfet_1p5u_2u_nf1 nfet_1p5u_2u_nf1 nfet_1p5u_2u_nf1 nfet_1p5u_2u_nf1 nfet_1p5u_2u_dum}
set n_roles {DUM NBIAS_A NSRC_A NSRC_B NBIAS_B DUM}

set xi 0
set i 0
foreach cell $n_order role $n_roles {
    set xpos [expr {$xi - $nx0}]
    set ypos [expr {0 - $ny0}]
    getcell $cell
    move origin $xpos $ypos
    puts "  Placed $cell ($role) at ([expr {$xpos*0.01}]um, [expr {$ypos*0.01}]um)"
    set xi [expr {$xi + $n_cell_w + $n_gap}]
    incr i
}

set total_n_w [expr {6 * $n_cell_w}]
set n_mid_y [expr {($n_cell_h) / 2}]

label "VSS" center [expr {$total_n_w / 2}] [expr {$n_cell_h + 50}]
label "nbias" center [expr {$n_cell_w + $n_cell_w/2}] $n_mid_y
label "nbias" center [expr {4 * $n_cell_w + $n_cell_w/2}] $n_mid_y
label "nsrc_g" center [expr {2 * $n_cell_w + $n_cell_w/2}] $n_mid_y
label "nsrc_g" center [expr {3 * $n_cell_w + $n_cell_w/2}] $n_mid_y

save cp_nmos_array
puts "cp_nmos_array saved with [expr {6}] nfet instances in common-centroid"

drc euclidean on
drc check
set cp_nmos_drc [drc list count total]
puts "cp_nmos_array DRC: $cp_nmos_drc violations"

puts ""
puts "==== SUMMARY ===="
puts "pfet_4u_2u_nf4 DRC:  $p_drc violations"
puts "nfet_1p5u_2u_nf1 DRC: $n_drc violations"
puts "cp_pmos_array DRC:   $cp_pmos_drc violations"
puts "cp_nmos_array DRC:   $cp_nmos_drc violations"
puts "=== CP array generation complete ==="
quit
