# Auto-generated by gen_pwm_hex.py — do not edit.
PASS_PC         = 0x00001130
FAIL_PC         = 0x00001128
ISR_PC          = 0x00001004
CONFIG_DONE_PC  = 0x000010a0
IRQ_READY_PC    = 0x000010c8
PRESCALE_VAL    = 3
PERIOD_VAL      = 20
DUTY_VAL        = 8
CTRL_VAL        = 0x00000001
PERIOD_CYCLES   = 80
ISR_FLAG_WI     = 310
ISR_COUNT_WI    = 311
WFI_POLL_LIMIT  = 4000
