/* =====================================================================
 * memory_coalescer.c -- GPU-Lite memory coalescer, C source for Bambu HLS
 *                       (PandA 2024.10), GH #119 "NL -> C -> RTL" pilot.
 *
 * WHAT THIS IMPLEMENTS
 * --------------------
 * Serialises the 8 per-lane VLD/VST requests of one warp-wide memory
 * instruction into AXI4 single-beat transactions, and reassembles the
 * per-lane read data.
 *
 * Phase 4 default behaviour (GPU_ENABLE_COALESCE = 0): NO address merging
 * is performed. Exactly one AXI transaction is issued per ACTIVE lane, and
 * lanes are walked from lowest index to highest, skipping every lane whose
 * mask bit is 0.
 *
 *   IDLE -> find first active lane
 *        -> (load)  AR -> R        -> next active lane or DONE
 *        -> (store) AW -> W -> B   -> next active lane or DONE
 *   DONE: pulse done_o for one cycle, return to IDLE.
 *
 * The AR/R/AW/W/B beat sequencing, ARLEN=0 / AWLEN=0 hardwiring, and the
 * response-channel handshakes are NOT written here: they are generated by
 * Bambu from the `m_axi` interface pragma on `mem`. This C source is
 * responsible only for (a) which lanes are touched, (b) in what order, and
 * (c) load vs store. See ASSUMPTIONS.md, item "AXI channel protocol".
 *
 * HARDWARE INTERFACE MAPPING
 * --------------------------
 *   start_i  -> Bambu's generated `start_port` (invocation == start)
 *   done_o   -> Bambu's generated `done_port`  (return     == done)
 *   we_i     -> `we`   (0 = load, 1 = store)
 *   addr_i[] -> `a0..a7`   (per-lane BYTE address)
 *   wdata_i[]-> `w0..w7`
 *   mask_i[] -> `mask`, bit i = lane i active
 *   rdata_o[]-> `*r0..*r7`
 *   AXI4 master -> m_axi_gmem_* , inferred from `mem`
 *
 * `mem` is a word-addressed `unsigned *`; `a0..a7` are byte addresses. The
 * integrating wrapper ties the gmem base to 0, so `mem[a >> 2]` produces
 * AXI byte address `a`.
 *
 * Constraints honoured: plain C99, no dynamic allocation, no libc calls,
 * no floating point, no recursion.
 *
 * ASSUMPTIONS: every place the spec was silent is marked with an
 * `ASSUMPTION n:` comment below and repeated in ASSUMPTIONS.md.
 * ===================================================================== */

#pragma HLS interface port = mem mode = m_axi offset = direct bundle = gmem
#pragma HLS interface port = r0 mode = none
#pragma HLS interface port = r1 mode = none
#pragma HLS interface port = r2 mode = none
#pragma HLS interface port = r3 mode = none
#pragma HLS interface port = r4 mode = none
#pragma HLS interface port = r5 mode = none
#pragma HLS interface port = r6 mode = none
#pragma HLS interface port = r7 mode = none

#define N_LANES 8u

void memory_coalescer(unsigned *mem,
                      unsigned a0, unsigned a1, unsigned a2, unsigned a3,
                      unsigned a4, unsigned a5, unsigned a6, unsigned a7,
                      unsigned w0, unsigned w1, unsigned w2, unsigned w3,
                      unsigned w4, unsigned w5, unsigned w6, unsigned w7,
                      unsigned mask, unsigned we,
                      unsigned *r0, unsigned *r1, unsigned *r2, unsigned *r3,
                      unsigned *r4, unsigned *r5, unsigned *r6, unsigned *r7)
{
   /* Local arrays are allowed (only the PARAMETERS are shape-constrained).
    * These are fully-indexed-by-constant after the loop is scheduled, so they
    * become wires/registers, not a RAM. */
   unsigned addr[N_LANES];
   unsigned wdata[N_LANES];
   unsigned rdata[N_LANES];
   unsigned lane;
   unsigned lane_active;

   addr[0] = a0; addr[1] = a1; addr[2] = a2; addr[3] = a3;
   addr[4] = a4; addr[5] = a5; addr[6] = a6; addr[7] = a7;

   wdata[0] = w0; wdata[1] = w1; wdata[2] = w2; wdata[3] = w3;
   wdata[4] = w4; wdata[5] = w5; wdata[6] = w6; wdata[7] = w7;

   /* ASSUMPTION 1 -- rdata_o for a lane that issues no read.
    * The spec defines rdata_o only as "per-lane read results" and never says
    * what an inactive lane, or ANY lane during a store, should present. We
    * drive 0. Rationale: a defined constant is cheaper than a hold register
    * (no extra state), it is deterministic for the equivalence testbench, and
    * it cannot be mistaken for stale data from a previous warp instruction.
    * The alternative (hold last value) was rejected because it makes the
    * block's output depend on request history, which is harder to verify and
    * which the spec gives no reason to want. */
   for(lane = 0u; lane < N_LANES; ++lane)
   {
      rdata[lane] = 0u;
   }

   /* ASSUMPTION 2 -- mask == 0 (no active lane).
    * The spec's FSM says "IDLE -> find first active lane"; it does not say
    * what happens when there is none. We issue zero AXI transactions and
    * complete immediately (loop body never fires), i.e. IDLE -> DONE. This
    * is the only behaviour consistent with "one AXI transaction per ACTIVE
    * lane" -- zero active lanes means zero transactions -- and it avoids
    * deadlocking the warp scheduler waiting for a done_o that never comes. */

   /* ASSUMPTION 3 -- lane ordering is enforced structurally, not by a pragma.
    * The spec mandates strict low-to-high lane order and one transaction per
    * active lane. In C that ordering only survives to RTL if the accesses are
    * not reordered by the scheduler. We deliberately add NO unroll/pipeline
    * pragma: adding one is what would BREAK the ordering requirement, not
    * what preserves it. Ordering is instead guaranteed by two structural
    * facts: (a) all accesses go through the single `gmem` bundle, so there is
    * exactly one AXI-master functional unit and every access is serialised on
    * it; (b) the addresses are runtime values Bambu cannot disambiguate, so
    * it must preserve program order across them.
    * MEASURED (Bambu 2024.10, flags as in hls/bambu.mk): Bambu fully unrolled
    * this loop -- the datapath contains 8 `ui_pointer_plus_expr_FU` address
    * adders and 8 `read_cond_FU` branch units, i.e. one per lane -- but it
    * kept them as a SEQUENTIAL chain of 8 conditional blocks (47 FSM states,
    * 33 control steps), which is exactly the specified lane-0-to-lane-7 walk.
    * Unrolling here is a scheduling detail, not a behavioural change. If the
    * flag set in hls/bambu.mk ever changes, re-check this against the
    * generated Verilog -- it is not something the C can assert. */

   /* ASSUMPTION 4 -- `we` is per-REQUEST, not per-lane.
    * The interface gives one `we_i` bit for the whole request (matching the
    * VLD/VST instruction opcode), so a request is entirely loads or entirely
    * stores. Mixed load/store within one request is not representable and is
    * not attempted. Any non-zero `we` is treated as "store" (we test `we`
    * for truth rather than `we == 1`) so that a wrapper driving 0xFFFFFFFF
    * or a sign-extended flag still behaves as a store. */

   /* ASSUMPTION 5 -- address alignment.
    * The spec says addresses are 32-bit byte addresses and that transfers are
    * 32-bit single beats, but is silent on misaligned addresses. Phase 4 has
    * no fault model (the spec says all error responses are ignored), so there
    * is no channel on which to report a misaligned access. We therefore treat
    * every address as naturally word-aligned and simply drop the low two bits
    * via `>> 2`. A misaligned address silently accesses the containing word.
    * This matches "Naturally aligned memory accesses only" elsewhere in the
    * project and costs no hardware. */

   /* ASSUMPTION 6 -- error responses.
    * The spec: "All error responses (rresp, bresp) are accepted and silently
    * ignored -- Phase 4 has no fault model." There is consequently NO C-level
    * code for them: a C pointer dereference has no error return, so Bambu's
    * generated AXI master already accepts and discards RRESP/BRESP. Nothing
    * to write, and nothing that could be written. */

   /* ASSUMPTION 7 -- byte enables / WSTRB.
    * All accesses are full 32-bit words (`unsigned`), so WSTRB is all-ones on
    * every write beat. The spec gives no sub-word / masked-store operation
    * (VST is word-granular), so no partial-word path exists. */

   for(lane = 0u; lane < N_LANES; ++lane)
   {
      lane_active = (mask >> lane) & 1u;

      if(lane_active)
      {
         if(we)
         {
            /* Store lane: AW -> W -> B, single beat, AWLEN = 0. */
            mem[addr[lane] >> 2] = wdata[lane];
         }
         else
         {
            /* Load lane: AR -> R, single beat, ARLEN = 0. */
            rdata[lane] = mem[addr[lane] >> 2];
         }
      }
   }

   /* DONE: all per-lane results published together. Bambu raises done_port
    * for one cycle on return, which is exactly the spec's
    * "assert done_o for one cycle, then return to IDLE". */
   *r0 = rdata[0]; *r1 = rdata[1]; *r2 = rdata[2]; *r3 = rdata[3];
   *r4 = rdata[4]; *r5 = rdata[5]; *r6 = rdata[6]; *r7 = rdata[7];
}
