"""
test_boot.py — Phase 5 (M9) SoC boot test.

Drives tb_soc_top: clock generation, 5-cycle reset, then monitors
commit_valid_o / commit_pc_o against the SoCModel golden PC stream.
Asserts final SRAM state matches reference sentinels.

Boot-stability gate: repeated boot attempts (default 100) with varied
reset-phase offset and per-attempt seed — all must pass with 0 failures.

BLOCKER NOTE (2026-06-03):
  This test is written and structurally correct, but cannot pass until
  fix_request fr_null_20260603_052800_00 is resolved:
    - CPU resets at PC=0x0000_0000 (hardcoded in rv32i_pipeline_if.sv:65)
    - Boot ROM is at 0x0000_1000
    - First CPU fetch goes to unmapped address → DECERR → CPU spins at mtvec=0
  Required RTL fix: add RESET_PC parameter to rv32i_pipeline_if / rv32i_core /
  rv32i_cpu_top and set it to 0x0000_1000 in soc_top.
  See design_state.json fix_requests[] for full details.
"""

import os
import random
import sys
from pathlib import Path

import cocotb
from cocotb.triggers import RisingEdge, ReadOnly, ClockCycles

# Project root on Python path so model imports work
_ROOT = Path(__file__).resolve().parent.parent.parent.parent
if str(_ROOT) not in sys.path:
    sys.path.insert(0, str(_ROOT))

from tb.models.soc_model import SoCModel
from soc_clocks import drive_soc_reset, start_soc_clocks

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------
CLK_PERIOD_NS   = 2          # 500 MHz — matches other SoC tests
ROM_BASE        = 0x0000_1000
SRAM_BASE       = 0x0000_2000
SENTINEL_0      = 0xDEAD_BEEF
SENTINEL_1      = 0x1234_5678

# Absolute path to the boot firmware hex image (generated by gen_boot_hex.py)
_BOOT_HEX = str(Path(__file__).parent / "boot_fw" / "boot.hex")

# Maximum cycles to wait for commit stream to complete
BOOT_TIMEOUT_CYCLES = 5000

# Boot-stability gate: number of repeated boot attempts
STABILITY_ATTEMPTS = 100

# ---------------------------------------------------------------------------
# Reference model — shared across all tests in this module
# ---------------------------------------------------------------------------
_SOC_MODEL = SoCModel(_BOOT_HEX)
_SOC_MODEL.boot(max_insns=200)
_GOLDEN_PCS   = list(_SOC_MODEL.committed_pcs)
_GOLDEN_STATE = _SOC_MODEL.final_state()


# ---------------------------------------------------------------------------
# Module-level task handle tracking (coroutine leakage guard per knowledge.md)
# ---------------------------------------------------------------------------
_active_tasks: list = []


def _kill_active_tasks() -> None:
    global _active_tasks
    for t in _active_tasks:
        t.kill()
    _active_tasks = []


# ---------------------------------------------------------------------------
# Boot-ROM backdoor loader
# ---------------------------------------------------------------------------
# Verilator bakes the boot_rom MEM_INIT_FILE string parameter in at
# elaboration and cocotb cannot override a string parameter at runtime, so the
# soc_boot Makefile target leaves the ROM image empty (all-zeros → every fetch
# decodes 0x00000000 as an illegal instruction → immediate trap to mtvec=0).
# Instead we backdoor-load boot.hex directly into the boot_rom memory array via
# the --public-flat-rw hierarchy handle.  boot_rom.mem is initialised in an
# initial block and is NOT cleared on reset, so depositing the words before
# reset release is sufficient and persistent.
_BOOT_WORDS: list | None = None


def _rom_words() -> list:
    """Parse boot.hex into a list of 32-bit words (one per non-comment line)."""
    global _BOOT_WORDS
    if _BOOT_WORDS is None:
        words: list = []
        with open(_BOOT_HEX) as f:
            for line in f:
                tok = line.strip()
                if not tok or tok.startswith("//") or tok.startswith("@"):
                    continue
                words.append(int(tok, 16))
        _BOOT_WORDS = words
    return _BOOT_WORDS


def _load_rom(dut) -> None:
    """Backdoor-load the firmware image into tb_soc_top.u_soc.u_boot_rom.mem."""
    mem = dut.u_soc.u_boot_rom.mem
    for i, word in enumerate(_rom_words()):
        mem[i].value = word


# ---------------------------------------------------------------------------
# Setup helper
# ---------------------------------------------------------------------------
async def _setup(dut, *, reset_extra_cycles: int = 0):
    """Start clock, idle APB + SPI inputs, apply reset, release.

    reset_extra_cycles: add N extra reset cycles before release (used by the
    stability gate to vary reset phase).
    """
    _kill_active_tasks()

    clk_task, cpu_clk_task = start_soc_clocks(dut, CLK_PERIOD_NS)
    _active_tasks.append(clk_task)
    _active_tasks.append(cpu_clk_task)

    # Idle all inputs
    drive_soc_reset(dut, True)
    dut.apb_paddr_i.value   = 0
    dut.apb_psel_i.value    = 0
    dut.apb_penable_i.value = 0
    dut.apb_pwrite_i.value  = 0
    dut.apb_pwdata_i.value  = 0
    dut.uart_rx_i.value     = 1   # idle high
    dut.spi_miso_i.value    = 0

    # Backdoor-load firmware into boot ROM (string MEM_INIT_FILE param cannot be
    # overridden at runtime under Verilator — see _load_rom).
    _load_rom(dut)

    # Assert reset for 5 + extra cycles
    for _ in range(5 + reset_extra_cycles):
        await RisingEdge(dut.clk_i)

    drive_soc_reset(dut, False)

    # 2-cycle settling after reset release
    for _ in range(2):
        await RisingEdge(dut.clk_i)


# ---------------------------------------------------------------------------
# Scoreboard helper
# ---------------------------------------------------------------------------
async def _collect_commits(dut, expected_pcs: list[int], timeout: int) -> dict:
    """Collect committed PCs from DUT commit bus; compare against expected.

    Returns dict with keys: pass (bool), mismatches (list), collected (list).
    """
    collected: list[int] = []
    mismatches: list[str] = []
    n_expected = len(expected_pcs)

    for _ in range(timeout):
        await RisingEdge(dut.clk_i)
        await ReadOnly()
        if dut.commit_valid_o.value:
            pc = int(dut.commit_pc_o.value)
            idx = len(collected)
            collected.append(pc)
            if idx < n_expected:
                exp = expected_pcs[idx]
                if pc != exp:
                    mismatches.append(
                        f"commit[{idx}]: got 0x{pc:08x}, expected 0x{exp:08x}"
                    )
            else:
                mismatches.append(
                    f"commit[{idx}]: extra commit 0x{pc:08x} (expected {n_expected} total)"
                )
            if len(collected) >= n_expected:
                break

    if len(collected) < n_expected:
        mismatches.append(
            f"timeout: collected {len(collected)}/{n_expected} commits"
        )

    return {
        "pass":       len(mismatches) == 0,
        "mismatches": mismatches,
        "collected":  collected,
    }


# ---------------------------------------------------------------------------
# Test 1: single boot — PC scoreboard + SRAM state check
# ---------------------------------------------------------------------------
@cocotb.test()
async def test_boot_pc_scoreboard(dut):
    """Boot the SoC, verify every committed PC matches the golden model."""
    dut._log.info(f"Golden PC stream ({len(_GOLDEN_PCS)} PCs): "
                  + ", ".join(f"0x{p:08x}" for p in _GOLDEN_PCS))

    await _setup(dut)

    result = await _collect_commits(dut, _GOLDEN_PCS, BOOT_TIMEOUT_CYCLES)

    for msg in result["mismatches"]:
        dut._log.error(f"SCOREBOARD MISMATCH: {msg}")

    dut._log.info(f"Collected {len(result['collected'])} commits, "
                  f"{len(result['mismatches'])} mismatches")

    assert result["pass"], (
        f"PC scoreboard FAIL — {len(result['mismatches'])} mismatch(es):\n"
        + "\n".join(result["mismatches"])
    )
    dut._log.info("test_boot_pc_scoreboard PASS")


# Sentinel SRAM word indices (word-addressed: index = (addr - SRAM_BASE) >> 2)
#   SRAM_BASE + 0x000 → word 0 → SENTINEL_0 (0xDEADBEEF)
#   SRAM_BASE + 0x004 → word 1 → SENTINEL_1 (0x12345678)
_SENTINEL_0_WI = 0   # SRAM[0x2000]
_SENTINEL_1_WI = 1   # SRAM[0x2004]


# ---------------------------------------------------------------------------
# Test 2: SRAM sentinel state check — DUT hardware SRAM backdoor readback
# ---------------------------------------------------------------------------
@cocotb.test()
async def test_boot_sram_sentinels(dut):
    """Fresh boot; verify DUT hardware SRAM[0x2000]=0xDEADBEEF and SRAM[0x2004]=0x12345678.

    Mechanism: backdoor read of dut.u_soc.u_sram.mem[] via Verilator
    --public-flat-rw hierarchy handle.  This is the same mechanism used by
    test_soc_stress.py (post-pass SRAM readout) and test_soc_coherency.py
    (kernel SRAM preload).  It directly reads the physical backing store of
    the behavioral SRAM DUT, confirming the sentinel values physically landed
    in hardware memory — not just that the correct SW instructions were
    dispatched.  An AXI read path is not used here because no TB AXI master
    exists in tb_soc_top.sv; the backdoor is the established pattern for all
    post-execution SRAM checks in this project.

    The golden reference model check is retained as a pre-flight guard before
    the DUT simulation runs, so a model bug is caught separately from a DUT bug.
    """
    dut._log.info("Checking golden SRAM state from reference model (pre-flight)...")
    golden_sram = _GOLDEN_STATE["sram_words"]

    # Pre-flight: confirm golden model has the expected sentinels
    w0_golden = golden_sram.get(SRAM_BASE, None)
    w1_golden = golden_sram.get(SRAM_BASE + 4, None)
    assert w0_golden == SENTINEL_0, (
        f"Golden model SRAM[0x2000] = 0x{w0_golden:08x}, expected 0x{SENTINEL_0:08x}"
    )
    assert w1_golden == SENTINEL_1, (
        f"Golden model SRAM[0x2004] = 0x{w1_golden:08x}, expected 0x{SENTINEL_1:08x}"
    )
    dut._log.info(
        "Golden SRAM sentinels confirmed: "
        f"[0x2000]=0x{SENTINEL_0:08X}, [0x2004]=0x{SENTINEL_1:08X}"
    )

    # Fresh boot of DUT — backdoor-loads firmware and releases reset
    await _setup(dut)

    # Wait for DUT to commit all golden PCs (firmware reaches EBREAK)
    collected_pcs: list[int] = []
    for _ in range(BOOT_TIMEOUT_CYCLES):
        await RisingEdge(dut.clk_i)
        await ReadOnly()
        if dut.commit_valid_o.value:
            collected_pcs.append(int(dut.commit_pc_o.value))
            if len(collected_pcs) >= len(_GOLDEN_PCS):
                break

    assert len(collected_pcs) == len(_GOLDEN_PCS), (
        f"Expected {len(_GOLDEN_PCS)} commits before SRAM check, "
        f"got {len(collected_pcs)}"
    )

    # Full PC-trace assert: every committed PC must match the golden model exactly.
    assert collected_pcs == _GOLDEN_PCS, (
        f"PC trace mismatch (got {len(collected_pcs)} commits, "
        f"expected {len(_GOLDEN_PCS)}):\n"
        + "\n".join(
            f"  [{i}] got=0x{got:08x} exp=0x{exp:08x}"
            + (" <-- MISMATCH" if got != exp else "")
            for i, (got, exp) in enumerate(zip(collected_pcs, _GOLDEN_PCS))
        )
        + (
            "\n  extra commits: "
            + ", ".join(f"0x{p:08x}" for p in collected_pcs[len(_GOLDEN_PCS):])
            if len(collected_pcs) > len(_GOLDEN_PCS) else ""
        )
    )

    # At this point the D-cache flush (CSRRW x0, 0x7C0, x0 at PC 0x101c) has
    # already committed: the pipeline stalls until the flush-all FSM transitions
    # out of CS_FLUSH_SCAN (all dirty lines written back).  However, the last
    # dirty-line burst (4 AXI4 beats) may still be propagating through the
    # axi4_crossbar W_DATA FSM to the sram_controller at commit time.  The EBREAK
    # commit (PC 0x1020, not in golden_pcs) is counted above — wait after all 8
    # commits for the final SRAM write burst to fully settle in the backing store.
    # 20 cycles is generous for a 4-beat AXI burst through the crossbar + SRAM.
    for _ in range(20):
        await RisingEdge(dut.clk_i)
    await ReadOnly()

    # DUT-side SRAM backdoor readback — same handle as test_soc_stress.py:202
    # and test_soc_coherency.py:128.  mem[] is word-indexed (32-bit words);
    # word_index = (byte_addr - SRAM_BASE) >> 2.
    sram = dut.u_soc.u_sram.mem
    dut_w0 = int(sram[_SENTINEL_0_WI].value)
    dut_w1 = int(sram[_SENTINEL_1_WI].value)

    dut._log.info(
        "DUT SRAM backdoor read: "
        f"mem[{_SENTINEL_0_WI}] (0x{SRAM_BASE:08x}) = 0x{dut_w0:08x}, "
        f"mem[{_SENTINEL_1_WI}] (0x{SRAM_BASE+4:08x}) = 0x{dut_w1:08x}"
    )

    # Hard assertions — fail if hardware SRAM does not hold the expected sentinels
    assert dut_w0 == SENTINEL_0, (
        f"DUT SRAM[0x{SRAM_BASE:08x}] (word {_SENTINEL_0_WI}) = 0x{dut_w0:08x}, "
        f"expected SENTINEL_0 = 0x{SENTINEL_0:08x}.  "
        f"SW x3, 0(x2) either did not complete AXI write or wrote to the wrong address."
    )
    assert dut_w1 == SENTINEL_1, (
        f"DUT SRAM[0x{SRAM_BASE+4:08x}] (word {_SENTINEL_1_WI}) = 0x{dut_w1:08x}, "
        f"expected SENTINEL_1 = 0x{SENTINEL_1:08x}.  "
        f"SW x4, 4(x2) either did not complete AXI write or wrote to the wrong address."
    )

    dut._log.info(
        "test_boot_sram_sentinels PASS — DUT hardware SRAM holds correct sentinels: "
        f"[0x{SRAM_BASE:08x}]=0x{dut_w0:08X}, [0x{SRAM_BASE+4:08x}]=0x{dut_w1:08X}"
    )


# ---------------------------------------------------------------------------
# Test 3: boot-stability gate — 100/100 attempts with varied reset phase/seed
# ---------------------------------------------------------------------------
@cocotb.test()
async def test_boot_stability_100(dut):
    """Repeat boot 100 times with varied reset-phase offset; 0 failures allowed.

    Each attempt:
      - random reset phase 0–7 extra cycles (varies AXI handshake timing)
      - random seed logged for reproducibility
      - full PC scoreboard check against golden model
    """
    failures: list[str] = []
    n_attempts = STABILITY_ATTEMPTS
    rng = random.Random()

    dut._log.info(f"Starting {n_attempts}-attempt boot-stability gate...")

    for attempt in range(n_attempts):
        seed = rng.randint(0, 0xFFFF_FFFF)
        rng.seed(seed)
        extra_rst = rng.randint(0, 7)

        dut._log.debug(f"Attempt {attempt+1}/{n_attempts} seed=0x{seed:08x} "
                       f"extra_rst={extra_rst}")

        await _setup(dut, reset_extra_cycles=extra_rst)

        result = await _collect_commits(dut, _GOLDEN_PCS, BOOT_TIMEOUT_CYCLES)

        if not result["pass"]:
            msg = (f"attempt {attempt+1} (seed=0x{seed:08x}, "
                   f"extra_rst={extra_rst}): "
                   + "; ".join(result["mismatches"]))
            failures.append(msg)
            dut._log.error(f"FAIL: {msg}")
        else:
            dut._log.debug(f"Attempt {attempt+1} PASS "
                           f"({len(result['collected'])} commits)")

        # Brief cooldown between attempts (let AXI transactions drain)
        await ClockCycles(dut.clk_i, 10)

    pass_count = n_attempts - len(failures)
    dut._log.info(f"Boot stability: {pass_count}/{n_attempts} PASS, "
                  f"{len(failures)} FAIL")

    assert len(failures) == 0, (
        f"Boot stability gate FAIL: {len(failures)}/{n_attempts} attempts failed:\n"
        + "\n".join(f"  {f}" for f in failures[:10])
        + (f"\n  ... and {len(failures)-10} more" if len(failures) > 10 else "")
    )

    dut._log.info(f"test_boot_stability_100 PASS: 100/100 boot attempts clean")
