"""
test_periph_loopback.py — Phase 5 (M9) SoC DMA + peripheral loopback test.

Drives tb_soc_top with a SELF-CHECKING RV32I firmware (periph_fw/periph_loopback.hex)
that, entirely via CPU MMIO through the real crossbar -> axi4_to_axilite ->
axi_lite_interconnect path:

  1. DMA mem->mem: writes a 4-word pattern into SRAM src (0x2000), programs the
     DMA engine (SRC/DST/LEN), pulses start, polls STATUS done, then loads the
     dst region (0x2040) back and compares word-by-word.
  2. UART internal loopback (CTRL[4]=1): transmits a byte, polls rx_valid, reads
     it back, compares.
  3. SPI internal loopback (CTRL[4]=1): transmits a byte, polls rx_valid, reads
     it back, compares.

On full success the firmware jumps to PASS_PC then EBREAKs; on any failure
(including bounded-poll timeout) it jumps to FAIL_PC then EBREAKs.

GOLDEN-MODEL NOTE:
  SoCModel cannot be used here — its _SoCMemoryAdapter raises ValueError on any
  0x2000_xxxx (peripheral MMIO) access. The firmware is therefore self-checking
  and the testbench scoreboards commit_pc_o for PASS_PC / FAIL_PC. As an
  additional independent check, the DMA destination SRAM region is backdoor-read
  and compared against the source region after PASS.

Firmware ROM image is backdoor-loaded into u_boot_rom.mem (Verilator bakes the
MEM_INIT_FILE string parameter at elaboration; see test_boot.py for rationale).
"""

import sys
from pathlib import Path

import cocotb
from cocotb.triggers import RisingEdge, ReadOnly

from soc_clocks import drive_soc_reset, start_soc_clocks

# Project root on Python path so imports work
_ROOT = Path(__file__).resolve().parent.parent.parent.parent
if str(_ROOT) not in sys.path:
    sys.path.insert(0, str(_ROOT))

from tb.cocotb.soc.periph_fw.periph_fw_addrs import (
    PASS_PC,
    FAIL_PC,
    DMA_SRC_IDX,
    DMA_DST_IDX,
)

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------
CLK_PERIOD_NS = 2  # 500 MHz — matches other SoC tests

# Firmware hex image (generated by periph_fw/gen_periph_hex.py)
_FW_HEX = str(Path(__file__).parent / "periph_fw" / "periph_loopback.hex")

# Generous bound: UART/SPI loopback bit-bangs at 16 clk/bit, so a full run
# (DMA + UART byte + SPI byte + polling) takes tens of thousands of cycles.
PERIPH_TIMEOUT_CYCLES = 200_000

# Number of DMA words copied (must match firmware)
DMA_N_WORDS = 4


# ---------------------------------------------------------------------------
# Boot-ROM backdoor loader (see test_boot.py for rationale)
# ---------------------------------------------------------------------------
_FW_WORDS: list | None = None


def _rom_words() -> list:
    """Parse periph_loopback.hex into a list of 32-bit words."""
    global _FW_WORDS
    if _FW_WORDS is None:
        words: list = []
        with open(_FW_HEX) as f:
            for line in f:
                tok = line.strip()
                if not tok or tok.startswith("//") or tok.startswith("@"):
                    continue
                words.append(int(tok, 16))
        _FW_WORDS = words
    return _FW_WORDS


def _load_rom(dut) -> None:
    """Backdoor-load the firmware image into tb_soc_top.u_soc.u_boot_rom.mem."""
    mem = dut.u_soc.u_boot_rom.mem
    words = _rom_words()
    assert len(words) <= len(mem), (
        f"Firmware image ({len(words)} words) exceeds boot ROM capacity "
        f"({len(mem)} words) — regenerate periph_loopback.hex"
    )
    for i, word in enumerate(words):
        mem[i].value = word


# ---------------------------------------------------------------------------
# Setup helper
# ---------------------------------------------------------------------------
async def _setup(dut) -> None:
    """Start clock, idle inputs, backdoor-load firmware, apply + release reset."""
    start_soc_clocks(dut, CLK_PERIOD_NS)

    # Idle all inputs
    drive_soc_reset(dut, True)
    dut.apb_paddr_i.value   = 0
    dut.apb_psel_i.value    = 0
    dut.apb_penable_i.value = 0
    dut.apb_pwrite_i.value  = 0
    dut.apb_pwdata_i.value  = 0
    dut.uart_rx_i.value     = 1   # idle high (loopback is internal, but keep sane)
    dut.spi_miso_i.value    = 0

    _load_rom(dut)

    # Assert reset for 5 cycles
    for _ in range(5):
        await RisingEdge(dut.clk_i)

    drive_soc_reset(dut, False)

    # 2-cycle settling after reset release
    for _ in range(2):
        await RisingEdge(dut.clk_i)


# ---------------------------------------------------------------------------
# Test: DMA + UART + SPI loopback via self-checking firmware
# ---------------------------------------------------------------------------
@cocotb.test()
async def test_periph_loopback(dut):
    """Run self-checking firmware; require PASS_PC committed, FAIL_PC never seen."""
    await _setup(dut)

    saw_pass = False
    last_pc = 0
    recent: list = []
    for _ in range(PERIPH_TIMEOUT_CYCLES):
        await RisingEdge(dut.clk_i)
        await ReadOnly()
        if dut.commit_valid_o.value:
            pc = int(dut.commit_pc_o.value)
            last_pc = pc
            recent.append(pc)
            if len(recent) > 16:
                recent.pop(0)
            assert pc != FAIL_PC, (
                f"firmware reached FAIL_PC at 0x{pc:08x} — a DMA/UART/SPI "
                f"loopback check failed (or a bounded poll timed out)"
            )
            if pc == PASS_PC:
                saw_pass = True
                break

    if not saw_pass:
        dut._log.info(
            "last_pc=0x%08x; recent committed PCs: %s",
            last_pc, " ".join(f"0x{p:08x}" for p in recent),
        )

    assert saw_pass, (
        f"PASS_PC (0x{PASS_PC:08x}) never committed within "
        f"{PERIPH_TIMEOUT_CYCLES} cycles"
    )

    # Independent DMA data check: destination SRAM region must equal source.
    sram = dut.u_soc.u_sram.mem
    for i in range(DMA_N_WORDS):
        src = int(sram[DMA_SRC_IDX + i].value)
        dst = int(sram[DMA_DST_IDX + i].value)
        assert src == dst, (
            f"DMA dst[{i}] (SRAM word {DMA_DST_IDX + i}) = 0x{dst:08x} != "
            f"src[{i}] (SRAM word {DMA_SRC_IDX + i}) = 0x{src:08x}"
        )
