# Auto-generated by gen_coherency_hex.py — do not edit.
PASS_PC      = 0x00001234
FAIL_PC      = 0x0000122c
SRC_IDX      = 64    # SRAM word index for src buffer
DST_IDX      = 80    # SRAM word index for dst buffer
KERNEL_IDX   = 128  # SRAM word index for kernel image
N_SRC_WORDS  = 8
SRC_BASE     = 0x00002100
DST_BASE     = 0x00002140
KERNEL_PC    = 0x00002200
