# Auto-generated by gen_cpu_gpu_irq_hex.py — do not edit.
PASS_PC      = 0x000012e0
FAIL_PC      = 0x000012d8
ISR_PC       = 0x00001004
SRC_IDX      = 96    # SRAM word index for src buffer
DST_IDX      = 112    # SRAM word index for dst buffer
KERNEL_IDX   = 160  # SRAM word index for kernel image
ISR_FLAG_WI  = 200   # SRAM word index for ISR-ran flag
N_SRC_WORDS  = 8
SRC_BASE     = 0x00002180
DST_BASE     = 0x000021c0
KERNEL_PC    = 0x00002280
ISR_FLAG_ADDR = 0x00002320
