#!/usr/bin/env python3
"""Source-idiom checker for the Synlig struct-member select defects (bead ainf).

Background (docs/SYNLIG_STRUCT_SELECT_AINF.md): the Synlig frontend mis-elaborates
  D1  s.m[hi:lo] / s.m[i]  when the struct TYPE has exactly two members declared with a packed range
  D2  y.m[hi:lo] = v       (LHS part-select of a struct member), for any struct type
and the damage can be fully silent.  sv2v is unaffected.  This checker is a tripwire on the
SOURCE idiom; it does not elaborate anything.

It reports three things for the RTL tree:
  1. every `<expr>.member[...]` select (the "sites"),
  2. every packed/unpacked struct typedef with exactly two ranged members ("D1-hot types"),
  3. every site that is on the LHS of an assignment ("D2 sites").
and compares them with a baseline file (`tools/verif/struct_member_select_baseline.txt`): a hit
whose normalised text is not in the baseline is NEW and fails the check (exit 1).  A baseline entry
that no longer matches anything is reported as stale (exit 0, printed with -v).

usage: check_struct_member_select.py [--root DIR] [--baseline FILE] [--write-baseline] [-v]
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

IDENT = r"[A-Za-z_][A-Za-z0-9_]*"
# base[idx]*.member(.member)*  followed by a bracket select
SITE_RE = re.compile(rf"({IDENT}(?:\[[^\]]*\])*(?:\.{IDENT})+)\s*\[")
LHS_RE = re.compile(
    rf"^\s*(?:assign\s+)?({IDENT}(?:\[[^\]]*\])*(?:\.{IDENT})+)\s*\[[^\]]*\]\s*(?:<=|=(?!=))"
)
TYPEDEF_RE = re.compile(r"typedef\s+struct\s*(?:packed)?\s*(?:signed|unsigned)?\s*\{(.*?)\}\s*(\w+)\s*;", re.S)
RANGED_RE = re.compile(rf"^\s*(?:logic|bit|reg)\s*(?:signed\s+|unsigned\s+)?\[[^\]]+\]")


def strip_comments(text: str) -> str:
    text = re.sub(r"/\*.*?\*/", lambda m: "\n" * m.group(0).count("\n"), text, flags=re.S)
    return re.sub(r"//[^\n]*", "", text)


def ranged_member_count(body: str) -> int:
    count = 0
    for decl in body.split(";"):
        if RANGED_RE.match(decl):
            count += 1
    return count


def scan_file(path: Path, root: Path) -> tuple:
    rel = path.relative_to(root).as_posix()
    text = strip_comments(path.read_text(encoding="utf-8", errors="replace"))
    sites, lhs, hot = [], [], []
    for m in TYPEDEF_RE.finditer(text):
        if ranged_member_count(m.group(1)) == 2:
            hot.append(f"hot-type|{rel}|{m.group(2)}")
    for lineno, line in enumerate(text.splitlines(), 1):
        norm = " ".join(line.split())
        for sm in SITE_RE.finditer(line):
            sites.append((f"site|{rel}|{sm.group(1)}", lineno, norm))
        lm = LHS_RE.match(line)
        if lm:
            lhs.append((f"lhs|{rel}|{lm.group(1)}", lineno, norm))
    return sites, lhs, hot


def collect(root: Path) -> tuple:
    sites, lhs, hot = [], [], []
    for path in sorted((root / "rtl").rglob("*.sv")):
        s, lh, h = scan_file(path, root)
        sites += s
        lhs += lh
        hot += [(k, 0, "") for k in h]
    return sites, lhs, hot


def main(argv: list | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--root", default=".", help="repository root (default: cwd)")
    ap.add_argument("--baseline", default=None, help="baseline file")
    ap.add_argument("--write-baseline", action="store_true")
    ap.add_argument("-v", "--verbose", action="store_true")
    args = ap.parse_args(argv)
    root = Path(args.root).resolve()
    base_path = Path(args.baseline) if args.baseline else root / "tools/verif/struct_member_select_baseline.txt"

    sites, lhs, hot = collect(root)
    keys = sorted({k for k, _, _ in sites + lhs + hot})
    if args.write_baseline:
        base_path.write_text(
            "# known struct-member select sites (bead ainf); generated by check_struct_member_select.py\n"
            + "\n".join(keys)
            + "\n",
            encoding="utf-8",
        )
        print(f"wrote {len(keys)} entries to {base_path}")
        return 0
    known: set = set()
    if base_path.exists():
        known = {ln.strip() for ln in base_path.read_text(encoding="utf-8").splitlines() if ln.strip() and not ln.startswith("#")}
    new = [(k, ln, txt) for k, ln, txt in sites + lhs + hot if k not in known]
    stale = sorted(known - set(keys))
    for k, ln, txt in new:
        print(f"NEW  {k}  (line {ln}) {txt}")
    if args.verbose:
        for k in stale:
            print(f"STALE {k}")
        print(f"{len(sites)} select sites, {len(lhs)} LHS sites, {len(hot)} two-ranged-member struct types")
    if new:
        print(
            f"FAIL: {len(new)} new struct-member select hit(s). Synlig mis-elaborates these "
            "(docs/SYNLIG_STRUCT_SELECT_AINF.md): assign the member to a named wire first and select the wire.",
            file=sys.stderr,
        )
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
