// Synthesis blackbox stub for sram_1rw_256x32_freepdk45
// Generated by OpenRAM for FreePDK45; behavioral body removed for synthesis.
// Words: 256 | Word size: 32 | Ports: 1 RW

(* blackbox *)
module sram_1rw_256x32_freepdk45 (
    input         clk0,   // clock
    input         csb0,   // active-low chip select
    input         web0,   // active-low write enable
    input  [7:0]  addr0,  // 8-bit address (256 words)
    input  [31:0] din0,   // write data
    output [31:0] dout0   // read data (negedge-launched, valid before next posedge)
);
endmodule
