# Auto-generated by gen_periph_hex.py — do not edit.
PASS_PC     = 0x00001170
FAIL_PC     = 0x00001168
DMA_SRC_IDX = 0   # SRAM word index: (0x2000 - 0x2000) >> 2
DMA_DST_IDX = 16  # SRAM word index: (0x2040 - 0x2000) >> 2
